import type { Metadata } from "next"
import "./globals.css"
import React from "react"
import localFont from "next/font/local"

export const metadata: Metadata = {
  title: "Aurum Capital",
  description: "Generated by create next app",
}

const modaniRegular = localFont({
  src: "./fonts/MadaniArabicRegular.ttf",
  weight: "400",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={modaniRegular.className}> {children}</body>
    </html>
  )
}
